version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: basic-security-exercise-db
    environment:
      POSTGRES_DB: java-4-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
